### ISSUE TITLE
[TorchToLinalg] Issue Tracking for Convolution Support

### ISSUE THREAD

**Issue by zjgarvey** [llvm/torch-mlir#3858]
There is some missing support for lowering `aten.convolution` to linalg:

- [ ] Grouped convolution for `spatial_dims != 2`. E.g. <https://github.com/llvm/torch-mlir/issues/3429>
- [ ] "Fake" depthwise convolution, where input and output channels differ. <https://github.com/llvm/torch-mlir/issues/3429>
- [ ] 1-D (groupsize = 1) quantized convolution [see this code block](https://github.com/llvm/torch-mlir/blob/7058f456b8aed85f6f08a73034be4cfa714c267e/lib/Conversion/TorchToLinalg/Linear.cpp#L1127-L1173)
- [ ] 3-D depthwise convolution [see this code](https://github.com/llvm/torch-mlir/blob/7058f456b8aed85f6f08a73034be4cfa714c267e/lib/Conversion/TorchToLinalg/Linear.cpp#L1230)
- [ ] 1-D and 3-D quantized depthwise convolution [see this code](https://github.com/llvm/torch-mlir/blob/7058f456b8aed85f6f08a73034be4cfa714c267e/lib/Conversion/TorchToLinalg/Linear.cpp#L1236)

Please feel free to file issues for individual items and link them here.

**Comment by pdhirajkumarprasad** [comment]
Here are the issues that we are seeing in models

1>

```mlir
module {
  func.func @main_graph( %arg1: !torch.vtensor<[1,96,1,1],f32>) -> !torch.vtensor<[1,32,1,1],f32>  attributes {torch.onnx_meta.ir_version = 8 : si64, torch.onnx_meta.opset_version = 21 : si64, torch.onnx_meta.opset_versions = {ai.onnx.contrib = 1 : si64}, torch.onnx_meta.producer_name = "vai_q_onnx", torch.onnx_meta.producer_version = "1.17.0+5e1d84e"} {
    %54 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.0> : tensor<32x24x1x1xf32>} : () -> !torch.vtensor<[32,24,1,1],f32> 
    %57 = torch.operator "onnx.Constant"() {torch.onnx.value = dense<1.0> : tensor<32xf32>} : () -> !torch.vtensor<[32],f32> 
    %1070 = torch.operator "onnx.Conv"(%arg1, %54, %57) {torch.onnx.dilations = [1 : si64, 1 : si64], torch.onnx.group = 4 : si64, torch.onnx.kernel_shape = [1 : si64, 1 : si64], torch.onnx.pads = [0 : si64, 0 : si64, 0 : si64, 0 : si64], torch.onnx.strides = [1 : si64, 1 : si64]} : (!torch.vtensor<[1,96,1,1],f32>, !torch.vtensor<[32,24,1,1],f32>, !torch.vtensor<[32],f32>) -> !torch.vtensor<[1,32,1,1],f32> 
    return %1070 : !torch.vtensor<[1,32,1,1],f32>
  }
}
```

error
```
model.torch_onnx.mlir:5:13: error: 'linalg.generic' op write affecting operations on global resources are restricted to workgroup distributed contexts.
    %1070 = torch.operator "onnx.Conv"(%arg1, %54, %57) {torch.onnx.dilations = [1 : si64, 1 : si64], torch.onnx.group = 4 : si64, torch.onnx.kernel_shape = [1 : si64, 1 : si64], torch.onnx.pads = [0 : si64, 0 : si64, 0 : si64, 0 : si64], torch.onnx.strides = [1 : si64, 1 : si64]} : (!torch.vtensor<[1,96,1,1],f32>, !torch.vtensor<[32,24,1,1],f32>, !torch.vtensor<[32],f32>) -> !torch.vtensor<[1,32,1,1],f32> 
            ^
model.torch_onnx.mlir:5:13: note: see current operation: 
```
